export interface checkoutData {
    vanityName: string;
    mealPerDay: string;
    programLength: string;
    breakfastSelection: string;
    dietary: string[];
    allergies: string[];
    allergyNotes: string;
    snackProtein: number; 
    proteinSmoothy: number; 
    juice: number; 
    coffee: number; 
    email: string;
    zipCode: string;
    firstName: string;
    lastName: string;
    phone: string;
    address: string;
    suite: string;
    city: string;
    state: string;
    deliveryNotes: string;
    firstDeliveryDate: string;
    billingAddress: string;
    billingSuite: string;
    billingCity: string;
    billingState: string;
    billingZipCode: string;
}