const QUERIES = {
  // USERS_LIST: 'users-list',
  USERS_LIST: 'api/all-users',
  ACTIVITY_LIST: 'api/activity-list'
}

const ACTIVITIES = {
  account_recovered: 'Account has been recovered',
  account_not_recovered: 'Account not recovered',
  user_link_resent: 'Active user link has been resent',
  user_link_sent: 'Active user link has been sent',
  user_link_not_resent: 'Error during Active user link email process',
  allergies_updated: 'Allergies & dislikes have been updated',
  allergies_updated_error: 'Error: Not able to change Allergies & dislikes',
  card_added: 'Card has been added',
  default_card_updated: 'Default card has been changed',
  card_error: 'Error during add card process',
  invalid_password: 'Invalid password has been provided by user',
  new_password_sent: 'New password has been set and sent',
  user_added: 'New user has been added',
  user_subscribed: 'New user has been subscribed',
  alacarte_user_subscribed: 'User also subscribed to: A la carte',
  meal_user_subscribed: 'User also subscribed to:',
  thanks_giving_user_subscribed: 'New thanksgiving dinner order',
  christmas_dinner_user_subscribed: 'New Christmas Dinner order',
  valentines_dinner_user_subscribed: 'New Valentines Day Dinner order',
  password_updated: 'Password has been changed and sent',
  phone_updated: ':name phone number has been changed.',
  user_name_updated: 'User Name Updated',
  email_updated: ':name email has been changed.',
  logged_in: 'Successfully logged in',
  logged_out: 'Successfully logged out',
  subscription_paused: 'Successfully paused subscription',
  subscription_temprory_paused: 'Admin Temporarily Paused Subscription',
  user_subscription_temprory_paused: 'User Temporarily Paused Subscription',
  subscription_paused_before_first_delivery: 'Successfully paused subscription',
  subscription_resumed: 'User has resumed subscription',
  plan_swapped: ':name successfully changed their plan : ',
  plan_upgraded: ':name has upgraded their plan : ',
  plan_downgraded: ':name has downgraded their plan : ',
  password_not_recovered: 'Unable to recover password',
  address_updated: 'User address has been changed',
  delivery_notes_updated: 'User Delivery Notes has been updated',
  address_update_error: 'Error : Unable to change address',
  phone_number_error: 'Error : Unable to change phone number',
  user_name_update_error: 'Error : Unable to change user name',
  email_number_error: 'Error : Unable to change email',
  cancel_pause_later: 'User has canceled pause later request',
  resume_pause_later: 'User has canceled resume later request',
  allergies_notes_updated: 'User has changed allergies notes',
  juice_updated: ':name has changed their juice plan:',
  juice_upgraded: ':name has upgraded their juice plan',
  juice_downgraded: ':name has downgraded their juice plan',
  juice_added: ':name has added a juice plan',
  snack_added: ':name has added a snack plan',
  snack_updated: ':name has changed their snack plan:',
  snack_upgraded: ':name has upgraded their snack plan:',
  snack_downgraded: ':name has downgraded their snack plan:',
  juice_removed: ':name has removed their juice plan',
  snack_removed: ':name has removed their snack plan',
  coffee_added: ':name has added a cold brew coffee',
  coffee_updated: ':name has changed their no of cold brews',
  coffee_updated_custom: ':name has changed cold brews',
  coffee_upgraded: ':name has upgraded their cold brews',
  coffee_downgraded: ':name has downgraded their cold brews',
  coffee_removed: ':name has removed cold brew coffee',
  breakfast_removed: ':name has removed their breakfast option.',
  delivery_window_updated: 'Admin has updated Delivery Window of this user',
  breakfast_added: ':name has added their breakfast option.',
  redeem_triggered: 'Redeem option has been triggered',
  amount_credited: 'Amount has been credited',
  delivery_plan_added: 'Admin has added a special delivery plan for this user : ',
  delivery_plan_updated: 'Admin has updated special delivery plan of this user : ',
  delivery_plan_removed: 'Admin has removed special delivery plan of this user',
  started_signup: 'Failed to complete signup',
  macros_added: 'User has added the macros of their meal plan :',
  macros_updated: 'User has updated the macros of their meal plan : ',
  macros_upgraded: 'User has upgraded the macros of their meal plan : ',
  macros_downgraded: 'User has downgraded the macros of their meal plan : ',
  same_name: ':name same name share with other users:',
  same_address: ':name Same address share with other users',
  meals_updated: 'User has updated the meals of their plan : ',
  skip_week: 'Skipped Week',
  payment_failed: 'Payment has been failed',
  payment_retry: 'Failed Invoice has been charged',
  pause_delivery: 'Paused subscription',
  delivery_update: 'Start Date Change',
}


export { 
  QUERIES,
  ACTIVITIES
}
